services:
  python-greetings-dev:
    build: .
    image: sophie14/python-greetings
    container_name: python-greetings-dev
    ports:
      - 7001:3000

  python-greetings-stg:
    build: . 
    image: sophie14/python-greetings
    container_name: python-greetings-stg
    ports:
      - 7002:3000

  python-greetings-prd:
    build:
      context: .
      dockerfile: Dockerfile
    image: sophie14/python-greetings
    container_name: python-greetings-prd
    ports:
      - 7003:3000
